[package]
name = "oscar"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = { version = "0.4.39", features = ["alloc"] }
clap = { version = "4.5.23", features = ["derive"] }
dirs = "5.0.1"
ini = "1.3.0"
